apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-johto
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokedex-johto
  template:
    metadata:
      labels:
        app: pokedex-johto
    spec:
      containers:
      - image: ghcr.io/froissant/pokedex:main
        imagePullPolicy: Always
        name: pokedex-johto
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
          - configMapRef:
              name: pokedex-johto-cm
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
