apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokedex-app
  template:
    metadata:
      labels:
        app: pokedex-app
    spec:
      containers:
        - image: pokedex:0.1
          name: pokedex-app
          ports:
            - containerPort: 3000
