apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokedex-app
  template:
    metadata:
      labels:
        app: pokedex-app
    spec:
      containers:
        - image: ghcr.io/froissant/pokedex:sha256-d7a3f49f762e164b2493277992cddd4cb16c7d71d03e4f826e6786ba625fbd81
          name: pokedex-app
          ports:
            - containerPort: 3000
          env:
            - name: POKEDEX_NAME
              valueFrom:
                configMapKeyRef:
                  name: pokedex-app
                  key: POKEDEX_NAME
            - name: POKEDEX_START_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: pokedex-app
                  key: POKEDEX_START_NUMBER
            - name: POKEDEX_END_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: pokedex-app
                  key: POKEDEX_END_NUMBER
