apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokedex-app
  template:
    metadata:
      labels:
        app: pokedex-app
    spec:
      containers:
        - image: ghcr.io/froissant/pokedex:sha256-723cec7f6d1805c887635ba87b5166021d3a6285c4fb18bb086ae3972f442104
          name: pokedex-app
          ports:
            - containerPort: 3000
          env:
            - name: POKEDEX_NAME
              valueFrom:
                configMapKeyRef:
                  name: pokedex-app
                  key: POKEDEX_NAME
            - name: POKEDEX_START_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: pokedex-app
                  key: POKEDEX_START_NUMBER
            - name: POKEDEX_END_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: pokedex-app
                  key: POKEDEX_END_NUMBER
