apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokedex-app
  template:
    metadata:
      labels:
        app: pokedex-app
    spec:
      containers:
        - image: pokedex:latest
          name: pokedex-app
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: POKEDEX_NAME
              valueFrom:
                configMapKeyRef:
                  name: pokedex-app
                  key: POKEDEX_NAME
            - name: POKEDEX_START_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: pokedex-app
                  key: POKEDEX_START_NUMBER
            - name: POKEDEX_END_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: pokedex-app
                  key: POKEDEX_END_NUMBER
